name: Notify
on:
  workflow_call:

jobs:
  engine-wala-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Print the hello message
        run: |
          echo "Hello from cd docker engine!"

      - name: print 2
        run: |
          echo "hello again"

  # notify:
  #   needs: engine-wala-job
  #   if: always()
  #   uses: ./.github/workflows/reusable.yml
  #   with:
  #     var1: ${{ needs.engine-wala-job.result }}
  #     var2: 'engine-demo'
  #   secrets: inherit
