name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: 📣 Send teams notification
      uses: simbo/msteams-message-card-action@latest
      with:
        webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
        message: Hello world!