name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Print the hello message
      run: |
        echo "Hello World!"

    - name: 📣 Send teams notification
      uses: simbo/msteams-message-card-action@latest
      with:
        webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
        if: success()
        title: Pipeline name (Insights copilot Dev Pipeline)
        message: <p>Dev deployment successfully completed. Check the application below and provide your approval for QA deployment</p>
        color: ff69b4
        buttons: |
          Approve https://github.com/smvabi/environment-testing-01/actions


    - name: 📣 Send teams notification
      uses: simbo/msteams-message-card-action@latest
      with:
        webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
        if: failure()
        title: Pipeline name (Insights copilot Dev Pipeline)
        message: <p>Dev deployment has failed. Please find the issue deatils here and proceed to create Hotfix branch
        color: ff69b4
        buttons: |
          Approve https://github.com/smvabi/environment-testing-01/actions
