name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

    - name: Set URL Variable
      id: set_url
      run: echo "::set-output name=url::${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

    - name: Print the hello message
      run: |
        echo "Hello World!"

    - name: 📣 Send teams notification
      uses: simbo/msteams-message-card-action@latest
      if: success()
      with:
        webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
        title: Pipeline name (Insights copilot Dev Pipeline)
        message: <p>Dev deployment successfully completed. Check the application below and provide your approval for QA deployment</p>
        color: ff69b4
        buttons: |
          Approve ${{ steps.set_url.outputs.url }}


    - name: 📣 Send teams notification
      uses: simbo/msteams-message-card-action@latest
      if: failure()
      with:
        webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
        title: Pipeline name (Insights copilot Dev Pipeline)
        message: <p>Dev deployment has failed. Please find the issue deatils here and proceed to create Hotfix branch</p>
        color: ff0000
        buttons: |
          Issue ${{ steps.set_url.outputs.url }}
