name: Build
on:
  push:
    branches:
      - feat/AB#12345-trigger-workflow

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

    - name: Set URL Variable
      id: set_url
      run: echo "::set-output name=url::${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

    - name: Print the hello message
      run: |
        echo "Hello World!"

    - name: 📣 Send teams notification
      uses: simbo/msteams-message-card-action@latest
      if: success()
      with:
        webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
        title: Pipeline name (Insights copilot Dev Pipeline)
        message: >
          <pDev deployment successfully completed.
          <br>Check the application below and provide your approval for QA deployment</p>
        buttons: |
          Approve ${{ steps.set_url.outputs.url }}
          Open Application https://brave-plant-0672fef10.3.azurestaticapps.net/
        sections: |
          -
            activityTitle: Success
            activityImage: https://i.pngimg.me/thumb/f/350/m2i8i8b1i8m2K9H7.jpg
            

    - name: 📣 Send teams notification
      uses: simbo/msteams-message-card-action@latest
      if: failure()
      with:
        webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
        title: Pipeline name (Insights copilot Dev Pipeline)
        message: >
          <p style="color: #c30010;">Dev deployment has failed.
          <br>Please find the issue details here and proceed to create Hotfix branch</p>
        buttons: |
          Failure logs ${{ steps.set_url.outputs.url }}

        
  approval:
    runs-on: ubuntu-latest
    environment: demo-env
    needs: notify
    steps:
      - name: Approval Succeeded
        run: |
          echo "Approved"
