name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
            echo "Building..."
            exit 1

  success:
    name: One with everything
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always() && success()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          dry_run: false

  # notify_on_failure:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: always() && failure()
  #   steps:
  #     - name: Microsoft Teams Notification on Failure
  #       uses: skitionek/notify-microsoft-teams@master
  #       with:
  #         webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
  #         dry_run: false
  #         message: "Build failed!"