name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
            echo "Building..."
            exit 1

  notify_on_success:
    runs-on: ubuntu-latest
    steps:
      - name: Microsoft Teams Notification on Success
        uses: skitionek/notify-microsoft-teams@master
        if: success()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          message: "Build succeeded!"

  notify_on_failure:
    runs-on: ubuntu-latest
    steps:
      - name: Microsoft Teams Notification on Failure
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          message: "Build failed!"
