name: Notify
on:
  push:
    branches:
      - feat/AB#12345-trigger-workflow

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the hello message
        run: |
          echo "Hello World!"

      - name: print 2
        run: |
          echo "hello again"

  notify:
    needs: first-job
    if: always()
    uses: ./.github/workflows/reusable.yml
    with:
      var1: ${{ needs.first-job.result }}
      var2: 'demo'
    secrets: inherit

          