name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: 🪣 Set env vars
      run: |
        echo "MY_SPECIAL_BUTTON=Cool /" >> $GITHUB_ENV

    - name: 📣 Send teams notification
      uses: simbo/msteams-message-card-action@latest
      env:
        MY_AWESOME_BUTTON: Awesome/
      with:
        webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
        title: Hello world!
        message: <p>This is my <strong>awesome message!</strong></p>
        color: ff69b4
        buttons: |
          Click here!
          Or here… 
          This button will not be shown as it has no target URL
          ${{ env.MY_SPECIAL_BUTTON }}
          ${{ env.MY_AWESOME_BUTTON }}
