name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

    - name: 📣 Send teams notification
      uses: simbo/msteams-message-card-action@latest
      with:
        webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
        title: Pipeline name (Insights copilot Dev Pipeline)
        message: <p>Dev deployment successfully completed. Check the application below - and provide your approval via  for QA deployment</p>
        color: ff69b4
        buttons: |
          Approve https://github.com/smvabi/environment-testing-01/actions
