name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

    - name: Set URL Variable
      id: set_url
      run: echo "::set-output name=url::${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

    - name: Print the hello message
      run: |
        echo "Hello World!"
        exit 1

    - name: 📣 Send teams notification
      uses: simbo/msteams-message-card-action@latest
      if: success()
      with:
        webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
        title: Pipeline name (Insights copilot Dev Pipeline)
        message: <p>Dev deployment successfully completed. <br>Check the application below and provide your approval for QA deployment</p>
        color: 00ff00
        buttons: |
          Approve ${{ steps.set_url.outputs.url }}
          Summary https://brave-plant-0672fef10.3.azurestaticapps.net/


    - name: 📣 Send teams notification
      uses: simbo/msteams-message-card-action@latest
      if: failure()
      with:
        webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
        title: Pipeline name (Insights copilot Dev Pipeline)
        message: <p>Dev deployment has failed. <br>Please find the issue details here and proceed to create Hotfix branch</p>
        color: c30010
        buttons: |
          Failure logs ${{ steps.set_url.outputs.url }}

        
  approval:
    runs-on: ubuntu-latest
    environment: demo-env
    needs: notify
    steps:
      - name: Approval Succeeded
        run: |
          echo "Approved"
