name: Notify
on:
  push:
    branches:
      - feat/AB#12345-trigger-workflow

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Call cd docker engine
        uses: ./.github/workflows/cd-docker-engine.yml

      - name: Call cd docker backend
        uses: ./.github/workflows/cd-docker-backend.yml
        