name: workflow_01

on:
  workflow_dispatch:
    inputs:
      workflow:
        description: 'Workflow 2 which will be triggered'
        required: true
        default: 'workflow_02'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'smvabi'

      workflow2_repo_github:
        description: 'repo-name'
        required: true
        default: 'environment-testing-02'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: demo-env

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          curl -X POST \
          -H 'Authorization: Bearer ${{ secrets.G_ACCESS_TOKEN }}' \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Content-Type: application/json' \
          https://api.github.com/repos/${{ inputs.workflow2_github_account }}/${{ inputs.workflow2_repo_github }}/actions/workflows/${{ inputs.workflow }}/dispatches \
          --data '{"ref": "main", "inputs": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3
