name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: demo-env

    steps:
    - name: print
      run: echo "Hello"

  lint:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: print2
      run: echo "World"
