name: workflow_01

on:
  workflow_dispatch:
    inputs:
      workflow:
        description: 'Workflow in environment-testing-02 to be triggered'
        required: true
        default: 'workflow_02'  # Change this to the desired workflow name

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'smvabi'

      workflow2_repo_github:
        description: 'repo-name'
        required: true
        default: 'environment-testing-02'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: demo-env

    steps:
      - name: Trigger Workflow
        run: |
          curl -X POST https://api.github.com/repos/${{ inputs.workflow2_github_account }}/${{ inputs.workflow2_repo_github }}/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.G_ACCESS_TOKEN }} \
          --data '{"event_type": "trigger_workflow_event", "client_payload": { "workflow": "'${{ inputs.workflow }}'", "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3
