name: workflow_01

on:
  workflow_run:
    workflows: ["workflow_02"]
    types:
      - completed

jobs:
  trigger-workflow-02:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow_02
        run: |
          curl -X POST https://api.github.com/repos/smvabi/environment-testing-02/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.G_ACCESS_TOKEN }} \
          --data '{"event_type": "trigger_workflow_event", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
